# Generated by Django 4.2.3 on 2023-11-11 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('MD', 'Doctor of Medicine'), ('DO', 'Doctor of Osteopathic Medicine'), ('MBBS', 'Bachelor of Medicine, Bachelor of Surgery'), ('BDS', 'Bachelor of Dental Surgery'), ('PhD_Medicine', 'Doctor of Philosophy in Medicine'), ('DPM', 'Doctor of Podiatric Medicine'), ('DVM', 'Doctor of Veterinary Medicine'), ('DPT', 'Doctor of Physical Therapy'), ('OD', 'Doctor of Optometry'), ('DDS', 'Doctor of Dental Surgery'), ('DMD', 'Doctor of Dental Medicine'), ('DCh', 'Doctor of Surgery (Chirurgiae)'), ('DM', 'Doctor of Medicine (Various Specialties)'), ('MBChB', 'Bachelor of Medicine and Bachelor of Surgery'), ('BChD', 'Bachelor of Dental Science'), ('BMed', 'Bachelor of Medicine'), ('BSci (Med)', 'Bachelor of Science in Medicine'), ('BMBS', 'Bachelor of Medicine, Bachelor of Surgery'), ('BPT', 'Bachelor of Physiotherapy'), ('BN', 'Bachelor of Nursing'), ('BSN', 'Bachelor of Science in Nursing'), ('BNurs', 'Bachelor of Nursing Science'), ('PharmD', 'Doctor of Pharmacy'), ('PsyD', 'Doctor of Psychology'), ('DSc', 'Doctor of Science'), ('DSW', 'Doctor of Social Work'), ('JD', 'Juris Doctor (Doctor of Law)'), ('DVM', 'Doctor of Veterinary Medicine'), ('PharmD', 'Doctor of Pharmacy'), ('DEng', 'Doctor of Engineering'), ('DFA', 'Doctor of Fine Arts'), ('DMus', 'Doctor of Music'), ('DA', 'Doctor of Arts')], max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('doctor_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('address', models.TextField()),
                ('specialization', models.CharField(choices=[('cardiology', 'Cardiology'), ('dermatology', 'Dermatology'), ('endocrinology', 'Endocrinology'), ('gastroenterology', 'Gastroenterology'), ('hematology', 'Hematology'), ('infectious_diseases', 'Infectious Diseases'), ('neurology', 'Neurology'), ('oncology', 'Oncology'), ('orthopedics', 'Orthopedics'), ('pediatrics', 'Pediatrics'), ('psychiatry', 'Psychiatry'), ('pulmonology', 'Pulmonology'), ('rheumatology', 'Rheumatology'), ('urology', 'Urology'), ('ophthalmology', 'Ophthalmology'), ('otolaryngology', 'Otolaryngology'), ('gynecology', 'Gynecology'), ('obstetrics', 'Obstetrics'), ('emergency_medicine', 'Emergency Medicine'), ('family_medicine', 'Family Medicine'), ('internal_medicine', 'Internal Medicine'), ('anesthesiology', 'Anesthesiology'), ('radiology', 'Radiology'), ('pathology', 'Pathology'), ('physical_therapy', 'Physical Therapy'), ('sports_medicine', 'Sports Medicine'), ('allergy_immunology', 'Allergy and Immunology'), ('vascular_surgery', 'Vascular Surgery'), ('plastic_surgery', 'Plastic Surgery'), ('maxillofacial_surgery', 'Maxillofacial Surgery'), ('nephrology', 'Nephrology'), ('reproductive_medicine', 'Reproductive Medicine'), ('critical_care_medicine', 'Critical Care Medicine'), ('pain_management', 'Pain Management'), ('sleep_medicine', 'Sleep Medicine')], max_length=200)),
                ('phone_number', models.CharField(max_length=15)),
                ('degrees', models.ManyToManyField(related_name='degrees_of_doctors', to='base.degree')),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('organization_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('public_hospital', 'Public Hospital'), ('private_hospital', 'Private Hospital'), ('clinic', 'Clinic'), ('lab', 'Laboratory')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization_type', models.CharField(choices=[('cardiology_hospital', 'Cardiology Hospital'), ('orthopedics_hospital', 'Orthopedics Hospital'), ('neurology_hospital', 'Neurology Hospital'), ('pediatrics_hospital', 'Pediatrics Hospital'), ('oncology_hospital', 'Oncology Hospital'), ('gastroenterology_hospital', 'Gastroenterology Hospital'), ('dermatology_hospital', 'Dermatology Hospital'), ('radiology_hospital', 'Radiology Hospital'), ('obstetrics_and_gynecology_hospital', 'Obstetrics and Gynecology Hospital'), ('dental_clinic', 'Dental Clinic'), ('orthopedic_clinic', 'Orthopedic Clinic'), ('dermatology_clinic', 'Dermatology Clinic'), ('pediatric_clinic', 'Pediatric Clinic'), ('womens_health_clinic', "Women's Health Clinic"), ('internal_medicine_clinic', 'Internal Medicine Clinic'), ('urology_clinic', 'Urology Clinic'), ('psychiatric_clinic', 'Psychiatric Clinic'), ('ent_clinic', 'ENT Clinic'), ('cardiology_clinic', 'Cardiology Clinic'), ('clinical_pathology_lab', 'Clinical Pathology'), ('microbiology_lab', 'Microbiology'), ('chemistry_lab', 'Chemistry'), ('hematology_lab', 'Hematology'), ('immunology_lab', 'Immunology'), ('genetics_lab', 'Genetics'), ('cytology_lab', 'Cytology'), ('histopathology_lab', 'Histopathology'), ('virology_lab', 'Virology'), ('molecular_diagnostics_lab', 'Molecular Diagnostics')], max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(max_length=30, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('dob', models.DateField()),
                ('address', models.TextField()),
                ('symptoms', models.TextField()),
                ('phone_number', models.CharField(max_length=15)),
                ('doctor', models.ManyToManyField(related_name='doctors_of_patients', to='base.doctor')),
                ('organizations', models.ManyToManyField(related_name='organizations_of_patient', to='base.organization')),
            ],
        ),
        migrations.AddField(
            model_name='organization',
            name='specializations',
            field=models.ManyToManyField(related_name='specializations_of_organisation', to='base.specialization'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctors', to='base.organization'),
        ),
    ]
