# Generated by Django 4.2.3 on 2023-11-12 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_doctor_patient_doctors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='organizations',
        ),
        migrations.AddField(
            model_name='doctor',
            name='image',
            field=models.ImageField(default='base/male_doctor.png', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='organization_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.organization'),
        ),
        migrations.AddField(
            model_name='patient',
            name='image',
            field=models.ImageField(default='base/male_patient.png', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='patient',
            name='organization_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.organization'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='phone_number',
            field=models.CharField(max_length=10),
        ),
        migrations.RemoveField(
            model_name='patient',
            name='doctors',
        ),
        migrations.AddField(
            model_name='patient',
            name='doctors',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.doctor'),
        ),
    ]
