# Generated by Django 4.2.3 on 2023-11-12 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_doctor_organization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='organization_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='base.organization'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='doctors',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='base.doctor'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='organization_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='base.organization'),
        ),
        migrations.AlterField(
            model_name='specialization',
            name='specialization_type',
            field=models.CharField(choices=[('cardiology_hospital', 'Cardiology Hospital'), ('orthopedics_hospital', 'Orthopedics Hospital'), ('neurology_hospital', 'Neurology Hospital'), ('pediatrics_hospital', 'Pediatrics Hospital'), ('oncology_hospital', 'Oncology Hospital'), ('gastroenterology_hospital', 'Gastroenterology Hospital'), ('dermatology_hospital', 'Dermatology Hospital'), ('radiology_hospital', 'Radiology Hospital'), ('obstetrics_and_gynecology_hospital', 'Obstetrics and Gynecology Hospital'), ('dental_clinic', 'Dental Clinic'), ('orthopedic_clinic', 'Orthopedic Clinic'), ('dermatology_clinic', 'Dermatology Clinic'), ('pediatric_clinic', 'Pediatric Clinic'), ('womens_health_clinic', "Women's Health Clinic"), ('internal_medicine_clinic', 'Internal Medicine Clinic'), ('urology_clinic', 'Urology Clinic'), ('psychiatric_clinic', 'Psychiatric Clinic'), ('ent_clinic', 'ENT Clinic'), ('cardiology_clinic', 'Cardiology Clinic'), ('clinical_pathology_lab', 'Clinical Pathology Lab'), ('microbiology_lab', 'Microbiology Lab'), ('chemistry_lab', 'Chemistry Lab'), ('hematology_lab', 'Hematology Lab'), ('immunology_lab', 'Immunology Lab'), ('genetics_lab', 'Genetics Lab'), ('cytology_lab', 'Cytology Lab'), ('histopathology_lab', 'Histopathology Lab'), ('virology_lab', 'Virology Lab'), ('molecular_diagnostics_lab', 'Molecular Diagnostics Lab')], max_length=200, unique=True),
        ),
    ]
