# Generated by Django 4.2.3 on 2023-11-12 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_doctor_organization_id_alter_patient_doctors_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='doctors',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='organization_id',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='symptoms',
        ),
    ]
