# Generated by Django 4.2.3 on 2023-11-13 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_lab_report_organization_staff_remove_patient_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization_staff',
            name='designation',
            field=models.CharField(choices=[('nurse', 'Nurse'), ('lab_technician', 'Lab Technician'), ('pharmacist', 'Pharmacist'), ('radiologist', 'Radiologist'), ('physiotherapist', 'Physiotherapist'), ('dietitian', 'Dietitian'), ('paramedic', 'Paramedic'), ('medical_assistant', 'Medical Assistant'), ('sweeper', 'Sweeper'), ('ward_attendant', 'Ward Attendant'), ('security_guard', 'Security Guard'), ('receptionist', 'Receptionist'), ('housekeeping_staff', 'Housekeeping Staff'), ('ambulance_driver', 'Ambulance Driver')], default='nurse', max_length=20),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='organization_staff',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.RemoveField(
            model_name='patient_history',
            name='staff_id',
        ),
        migrations.AddField(
            model_name='patient_history',
            name='staff_id',
            field=models.ManyToManyField(blank=True, null=True, related_name='asscociated_staffs', to='base.organization_staff'),
        ),
    ]
