# Generated by Django 4.2.3 on 2023-11-13 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_organization_staff_designation_alter_doctor_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient_history',
            name='staff_id',
            field=models.ManyToManyField(related_name='asscociated_staffs', to='base.organization_staff'),
        ),
    ]
