# Generated by Django 4.2.3 on 2023-11-13 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_patient_history_staff_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient_history',
            name='lab_reports',
        ),
        migrations.AlterField(
            model_name='patient_history',
            name='patient_report_pdf',
            field=models.FileField(upload_to='patient_overall_report/'),
        ),
        migrations.DeleteModel(
            name='Lab_Report',
        ),
        migrations.AddField(
            model_name='patient_history',
            name='lab_reports',
            field=models.FileField(blank=True, null=True, upload_to='patient_lab_report/'),
        ),
    ]
