# Generated by Django 4.2.3 on 2023-11-13 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_remove_patient_history_lab_reports_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient_history',
            old_name='lab_reports',
            new_name='lab_reports_pdf',
        ),
    ]
