# Generated by Django 4.2.3 on 2023-11-14 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_customuserprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuserprofile',
            name='user_unique_id',
        ),
    ]
