# Generated by Django 4.2.3 on 2023-11-14 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_remove_customuserprofile_user_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient_history',
            name='staff_id',
            field=models.ManyToManyField(blank=True, null=True, related_name='asscociated_staffs', to='base.organization_staff'),
        ),
    ]
